# You can add one username per supported platform and one custom link
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective username
ko_fi: skvllface
custom: # Replace with your custom donation URL
